### ISSUE TITLE
tput error

### ISSUE THREAD

**Issue by kushfest** [deanochips/HLS-XMLTV-Docker#1]
Thank you for the official docker image. This seems to be working for me! I did notice this error a number of times in my logs:

`tput: No value for $TERM and no -T specified`

It doesn't appear to be impacting performance, but seemed worth calling to your attention. Hopefully an easy fix.

**Comment by deanochips** [comment]
it just because i used the ubuntu .bashrc, i have replaced it, it should stop this error.

but thanks for pointing it out

**Comment by kushfest** [comment]
Awesome! Is there a recommended way to pull the latest version of the script inside the docker container? I tried restarting the docker container, but I'm still seeing the error, which I'm guessing may mean the docker container isn't running the newest version of the script.

**Comment by deanochips** [comment]
just delete your current version container and image and re clone the repo and install again 

( remember to save your docker-compose.yml and once downloaded over write the downloaded version and run "bash build.sh")

it should just startup and use the existing config & concat list files and cache....
