### ISSUE TITLE
cache folder 'resource busy'

### ISSUE THREAD

**Issue by kushfest** [deanochips/HLS-XMLTV-Docker#3]
This error is the last line in my log when I build the docker image:

`mv: cannot move '/HLS-XMLTV---Home-Broadcasting-master/cache' to '/HLS-XMLTV/cache': Resource busy'`

I've seen it each time I've built the image, even when things have been working, so I don't think this actually impacts performance.

**Comment by deanochips** [comment]
should be sorted now,

not really a error it just that because we map a cache folder in docker-compose.yml it already exists in the docker so it can't created again when the app is unzipped and moved

as you said it does not effect anything
