### ISSUE TITLE
Build.sh Failing

### ISSUE THREAD

**Issue by dodge28** [deanochips/HLS-XMLTV-Docker#4]
Thank you for pulling all this together and making it available.

I have a problem when I run bash build.sh per your instruction. I looks like the program is not pulling or cannot find the fdk-aac-dev file:

Step 4/8 : RUN echo http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories ;  apk add --no-cache fdk-aac-dev  tini  procps  ffmpeg  bash  bash-completion  coreutils  ncurses  logrotate  python3  jq  htop  nano  findutils  nginx  youtube-dl  xmltv  socat
 ---> Running in c34e8c5ed1e5
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz

ERROR: unsatisfiable constraints:
  fdk-aac-dev (missing):
  required by: world[fdk-aac-dev]

ERROR: Service 'hls-xmltv' failed to build: The command '/bin/sh -c echo http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories ;  apk add --no-cache fdk-aac-dev  tini  procps  ffmpeg  bash  bash-completion  coreutils  ncurses  logrotate  python3  jq  htop  nano  findutils  nginx  youtube-dl  xmltv  socat' returned a non-zero code: 1

**Comment by deanochips** [comment]
one of the supporting packages moved repo to
http://dl-cdn.alpinelinux.org/alpine/edge/community.

i have updated the docker file and it now builds correctly

just re download,
